-- Seed production menus and dishes (idempotent).
-- Notes:
-- - Uses INSERT ... WHERE NOT EXISTS to be safe on re-runs.
-- - Uses dish.name and menu.name as natural keys for seeding.
-- - image_url uses Unsplash Source with keywords as requested.

-- 1) Menus (5 base + 2 time-based)
WITH seed_menus(name, start_time, end_time) AS (
    VALUES
        ('Закуски', NULL::time, NULL::time),
        ('Основні страви', NULL::time, NULL::time),
        ('Десерти', NULL::time, NULL::time),
        ('Напої', NULL::time, NULL::time),
        ('Дитяче меню', NULL::time, NULL::time),
        ('Сніданки', TIME '06:00', TIME '12:00'),
        ('Вечірні спеціалітети', TIME '18:00', TIME '23:59')
)
INSERT INTO menu(name, start_time, end_time)
SELECT sm.name, sm.start_time, sm.end_time
FROM seed_menus sm
WHERE NOT EXISTS (
    SELECT 1
    FROM menu m
    WHERE m.name = sm.name
      AND (
        (m.start_time IS NULL AND sm.start_time IS NULL) OR m.start_time = sm.start_time
      )
      AND (
        (m.end_time IS NULL AND sm.end_time IS NULL) OR m.end_time = sm.end_time
      )
);

-- 2) Dishes (~100) + base fields
WITH seed_dishes(name, description, price, image_url, is_available) AS (
    VALUES
        -- Закуски (20)
        ('Брускета з томатами та базиліком', 'Хрусткий хліб, томати, базилік та оливкова олія.', 135.00, 'https://source.unsplash.com/featured/?bruschetta', TRUE),
        ('Брускета з лососем та крем-сиром', 'Брускета з малосольним лососем, крем-сиром і лимоном.', 185.00, 'https://source.unsplash.com/featured/?salmon,bruschetta', TRUE),
        ('Тартар з яловичини', 'Класичний тартар із яловичини з каперсами та тостами.', 245.00, 'https://source.unsplash.com/featured/?beef,tartare', TRUE),
        ('Тартар з лосося', 'Ніжний тартар з лосося з авокадо та лаймом.', 255.00, 'https://source.unsplash.com/featured/?salmon,tartare', TRUE),
        ('Креветки темпура', 'Хрусткі креветки в клярі з соусом чилі-майо.', 235.00, 'https://source.unsplash.com/featured/?tempura,shrimp', TRUE),
        ('Курячі крильця BBQ', 'Запечені крильця в солодко-димному соусі BBQ.', 215.00, 'https://source.unsplash.com/featured/?bbq,chicken,wings', TRUE),
        ('Сирна тарілка', 'Асорті сирів з горіхами, медом та виноградом.', 295.00, 'https://source.unsplash.com/featured/?cheese,plate', TRUE),
        ('М''ясна тарілка', 'Прошуто, салямі, брезаола та мариновані оливки.', 315.00, 'https://source.unsplash.com/featured/?charcuterie,meat,plate', TRUE),
        ('Хумус з пітою', 'Кремовий хумус з оливковою олією та пітою.', 145.00, 'https://source.unsplash.com/featured/?hummus,pita', TRUE),
        ('Паштет з курячої печінки', 'Домашній паштет із цибульним конфі та тостами.', 165.00, 'https://source.unsplash.com/featured/?chicken,liver,pate', TRUE),
        ('Оселедець з цибулею та картоплею', 'Класична українська закуска з відвареною картоплею.', 155.00, 'https://source.unsplash.com/featured/?herring,potatoes', TRUE),
        ('Сало з часником та гірчицею', 'Сало зі спеціями, подається з чорним хлібом.', 145.00, 'https://source.unsplash.com/featured/?pork,fat,salo', TRUE),
        ('Вінегрет', 'Овочевий салат з буряком, квашеною капустою та огірком.', 125.00, 'https://source.unsplash.com/featured/?vinaigrette,salad', TRUE),
        ('Салат Грецький', 'Огірок, томат, оливки, фета та орегано.', 165.00, 'https://source.unsplash.com/featured/?greek,salad', TRUE),
        ('Салат Цезар з куркою', 'Ромейн, курка-гриль, пармезан та соус Цезар.', 195.00, 'https://source.unsplash.com/featured/?caesar,salad,chicken', TRUE),
        ('Салат Цезар з креветками', 'Ромейн, креветки, пармезан та соус Цезар.', 235.00, 'https://source.unsplash.com/featured/?caesar,salad,shrimp', TRUE),
        ('Салат Капрезе', 'Томати, моцарела, базилік та бальзамік.', 185.00, 'https://source.unsplash.com/featured/?caprese,salad', TRUE),
        ('Олів''є з куркою', 'Традиційний салат з куркою, горошком та солоним огірком.', 145.00, 'https://source.unsplash.com/featured/?olivier,salad', TRUE),
        ('Форшмак', 'Оселедець, яблуко та цибуля, подається з тостами.', 155.00, 'https://source.unsplash.com/featured/?herring,spread', TRUE),
        ('Мариновані оливки та маслини', 'Асорті оливок з травами та цитрусом.', 115.00, 'https://source.unsplash.com/featured/?olives,appetizer', TRUE),

        -- Сніданки (16)
        ('Сирники зі сметаною', 'Ніжні сирники зі сметаною та ягідним соусом.', 165.00, 'https://source.unsplash.com/featured/?syrniki,cheesecakes', TRUE),
        ('Вівсянка з ягодами та медом', 'Тепла вівсянка з сезонними ягодами та медом.', 145.00, 'https://source.unsplash.com/featured/?oatmeal,berries', TRUE),
        ('Гранола з йогуртом', 'Домашня гранола з йогуртом та фруктами.', 155.00, 'https://source.unsplash.com/featured/?granola,yogurt', TRUE),
        ('Яйця Бенедикт', 'Пашот, шинка, англійський мафін та соус голландез.', 215.00, 'https://source.unsplash.com/featured/?eggs,benedict', TRUE),
        ('Омлет з сиром та зеленню', 'Пухкий омлет із сиром та свіжою зеленню.', 165.00, 'https://source.unsplash.com/featured/?omelette', TRUE),
        ('Скрембл з лососем', 'Ніжний скрембл із лососем та тостом.', 235.00, 'https://source.unsplash.com/featured/?scrambled,eggs,salmon', TRUE),
        ('Шакшука', 'Яйця в пряному томатному соусі з зеленню.', 195.00, 'https://source.unsplash.com/featured/?shakshuka', TRUE),
        ('Тост з авокадо', 'Тост на заквасці з авокадо, лаймом та кунжутом.', 185.00, 'https://source.unsplash.com/featured/?avocado,toast', TRUE),
        ('Млинці з сиром', 'Тонкі млинці з солодким сиром та ваніллю.', 165.00, 'https://source.unsplash.com/featured/?crepes,cheese', TRUE),
        ('Млинці з лососем', 'Млинці з лососем, крем-сиром та кропом.', 215.00, 'https://source.unsplash.com/featured/?crepes,salmon', TRUE),
        ('Каша гречана з грибами', 'Гречка з печерицями та цибулею.', 155.00, 'https://source.unsplash.com/featured/?buckwheat,mushrooms', TRUE),
        ('Сендвіч з індичкою', 'Сендвіч з індичкою, сиром та овочами.', 195.00, 'https://source.unsplash.com/featured/?turkey,sandwich', TRUE),
        ('Круасан з мигдалем', 'Свіжий круасан з мигдальною начинкою.', 125.00, 'https://source.unsplash.com/featured/?almond,croissant', TRUE),
        ('Круасан з шинкою та сиром', 'Теплий круасан з шинкою та сиром.', 155.00, 'https://source.unsplash.com/featured/?croissant,ham,cheese', TRUE),
        ('Французькі тости', 'Тости з корицею, подаються з ягодами.', 175.00, 'https://source.unsplash.com/featured/?french,toast', TRUE),
        ('Йогурт з фруктами', 'Натуральний йогурт зі свіжими фруктами.', 135.00, 'https://source.unsplash.com/featured/?yogurt,fruit', TRUE),

        -- Основні страви (34)
        ('Борщ український', 'Традиційний борщ зі сметаною та пампушками.', 195.00, 'https://source.unsplash.com/featured/?borscht', TRUE),
        ('Солянка м''ясна', 'Насичений суп з кількох видів м''яса та оливками.', 205.00, 'https://source.unsplash.com/featured/?solyanka,soup', TRUE),
        ('Курячий бульйон з локшиною', 'Легкий бульйон з домашньою локшиною.', 165.00, 'https://source.unsplash.com/featured/?chicken,noodle,soup', TRUE),
        ('Грибний крем-суп', 'Крем-суп з печериць зі вершками та грінками.', 175.00, 'https://source.unsplash.com/featured/?mushroom,cream,soup', TRUE),
        ('Юшка з риби', 'Легка рибна юшка з зеленню та лимоном.', 185.00, 'https://source.unsplash.com/featured/?fish,soup', TRUE),
        ('Вареники з картоплею', 'Вареники з картоплею та смаженою цибулею.', 175.00, 'https://source.unsplash.com/featured/?varenyky', TRUE),
        ('Вареники з вишнею', 'Вареники з вишнею та сметаною.', 185.00, 'https://source.unsplash.com/featured/?dumplings,cherry', TRUE),
        ('Деруни зі сметаною', 'Картопляні деруни з хрусткою скоринкою.', 165.00, 'https://source.unsplash.com/featured/?potato,pancakes', TRUE),
        ('Котлета по-київськи', 'Куряча котлета з вершковим маслом та зеленню.', 255.00, 'https://source.unsplash.com/featured/?chicken,kyiv,cutlet', TRUE),
        ('Голубці', 'Капустяні рулетики з м''ясом та рисом у соусі.', 225.00, 'https://source.unsplash.com/featured/?cabbage,rolls', TRUE),
        ('Плов з куркою', 'Ароматний рис з куркою та спеціями.', 215.00, 'https://source.unsplash.com/featured/?pilaf,rice,chicken', TRUE),
        ('Паста Карбонара', 'Паста з гуанчале, яйцем та пармезаном.', 245.00, 'https://source.unsplash.com/featured/?carbonara,pasta', TRUE),
        ('Паста Болоньєзе', 'Паста з м''ясним соусом болоньєзе.', 235.00, 'https://source.unsplash.com/featured/?bolognese,pasta', TRUE),
        ('Паста Альфредо з куркою', 'Вершковий соус Альфредо та курка-гриль.', 245.00, 'https://source.unsplash.com/featured/?alfredo,pasta', TRUE),
        ('Різото з грибами', 'Кремове різото з грибами та пармезаном.', 255.00, 'https://source.unsplash.com/featured/?risotto,mushroom', TRUE),
        ('Різото з морепродуктами', 'Різото з креветками та кальмарами.', 295.00, 'https://source.unsplash.com/featured/?seafood,risotto', TRUE),
        ('Лазанья болоньєзе', 'Домашня лазанья з соусом болоньєзе та бешамель.', 285.00, 'https://source.unsplash.com/featured/?lasagna', TRUE),
        ('Стейк Рібай', 'Соковитий стейк рібай зі спеціями.', 495.00, 'https://source.unsplash.com/featured/?ribeye,steak', TRUE),
        ('Стейк Нью-Йорк', 'Класичний стейк з мармурової яловичини.', 465.00, 'https://source.unsplash.com/featured/?new,york,steak', TRUE),
        ('Свинячі реберця BBQ', 'Запечені реберця в соусі BBQ.', 365.00, 'https://source.unsplash.com/featured/?bbq,ribs', TRUE),
        ('Курка теріякі', 'Курка в соусі теріякі з рисом та кунжутом.', 265.00, 'https://source.unsplash.com/featured/?teriyaki,chicken', TRUE),
        ('Куряче філе гриль', 'Філе гриль із овочами та соусом.', 245.00, 'https://source.unsplash.com/featured/?grilled,chicken', TRUE),
        ('Лосось гриль', 'Філе лосося гриль з лимоном та зеленню.', 365.00, 'https://source.unsplash.com/featured/?grilled,salmon', TRUE),
        ('Філе тріски з пюре', 'Тріска в паніруванні з картопляним пюре.', 285.00, 'https://source.unsplash.com/featured/?cod,fish', TRUE),
        ('Мідії у вершковому соусі', 'Мідії з часником, вершками та зеленню.', 325.00, 'https://source.unsplash.com/featured/?mussels,cream', TRUE),
        ('Бургер з яловичиною', 'Котлета з яловичини, сир, соус та картопля фрі.', 285.00, 'https://source.unsplash.com/featured/?burger,beef', TRUE),
        ('Курячий бургер', 'Куряче філе в паніруванні, салат і соус.', 255.00, 'https://source.unsplash.com/featured/?chicken,burger', TRUE),
        ('Фіш-енд-чіпс', 'Хрустка риба з картоплею фрі та соусом тартар.', 275.00, 'https://source.unsplash.com/featured/?fish,and,chips', TRUE),
        ('Шніцель по-віденськи', 'Тонкий шніцель у паніруванні з лимоном.', 295.00, 'https://source.unsplash.com/featured/?wiener,schnitzel', TRUE),
        ('Бефстроганов', 'Яловичина у вершковому соусі з грибами.', 315.00, 'https://source.unsplash.com/featured/?beef,stroganoff', TRUE),
        ('Пельмені домашні', 'Пельмені з м''ясом, подаються зі сметаною.', 195.00, 'https://source.unsplash.com/featured/?pelmeni,dumplings', TRUE),
        ('Овочеве рагу', 'Тушковані сезонні овочі з травами.', 195.00, 'https://source.unsplash.com/featured/?vegetable,stew', TRUE),
        ('Стейк з цвітної капусти', 'Запечена цвітна капуста зі спеціями та соусом.', 215.00, 'https://source.unsplash.com/featured/?cauliflower,steak', TRUE),
        ('Гречка з тушкованою яловичиною', 'Гречка з ніжною яловичиною та підливою.', 245.00, 'https://source.unsplash.com/featured/?buckwheat,beef', TRUE),

        -- Десерти (16)
        ('Київський торт', 'Легендарний торт з безе та горіхами.', 185.00, 'https://source.unsplash.com/featured/?kyiv,cake', TRUE),
        ('Медовик', 'Торт медовик з ніжним кремом.', 165.00, 'https://source.unsplash.com/featured/?honey,cake', TRUE),
        ('Наполеон', 'Листковий торт з заварним кремом.', 165.00, 'https://source.unsplash.com/featured/?napoleon,cake', TRUE),
        ('Сирник львівський', 'Львівський сирник з шоколадною глазур''ю.', 175.00, 'https://source.unsplash.com/featured/?cheesecake', TRUE),
        ('Штрудель яблучний', 'Яблучний штрудель з корицею та ванільним соусом.', 165.00, 'https://source.unsplash.com/featured/?apple,strudel', TRUE),
        ('Тірамісу', 'Класичний італійський десерт з маскарпоне.', 185.00, 'https://source.unsplash.com/featured/?tiramisu', TRUE),
        ('Панна котта', 'Вершковий десерт з ягідним соусом.', 165.00, 'https://source.unsplash.com/featured/?panna,cotta', TRUE),
        ('Чізкейк Нью-Йорк', 'Кремовий чізкейк на пісочній основі.', 185.00, 'https://source.unsplash.com/featured/?new,york,cheesecake', TRUE),
        ('Брауні з морозивом', 'Шоколадний брауні з кулькою ванільного морозива.', 175.00, 'https://source.unsplash.com/featured/?brownie,ice,cream', TRUE),
        ('Шоколадний фондан', 'Теплий кекс з рідкою шоколадною серединкою.', 185.00, 'https://source.unsplash.com/featured/?chocolate,lava,cake', TRUE),
        ('Морозиво асорті', 'Асорті морозива з топінгом.', 135.00, 'https://source.unsplash.com/featured/?ice,cream', TRUE),
        ('Профітролі', 'Профітролі з заварним кремом.', 155.00, 'https://source.unsplash.com/featured/?profiteroles', TRUE),
        ('Макарони', 'Асорті французьких макаронів.', 165.00, 'https://source.unsplash.com/featured/?macarons', TRUE),
        ('Чізкейк з чорницею', 'Чізкейк з чорницею та вершковим кремом.', 195.00, 'https://source.unsplash.com/featured/?blueberry,cheesecake', TRUE),
        ('Пиріг з вишнею', 'Домашній пиріг з вишнею.', 155.00, 'https://source.unsplash.com/featured/?cherry,pie', TRUE),
        ('Крем-брюле', 'Класичний крем-брюле з карамельною скоринкою.', 185.00, 'https://source.unsplash.com/featured/?creme,brulee', TRUE),

        -- Напої (14) + частина буде також у сніданках/вечірніх
        ('Еспресо', 'Класичний еспресо.', 65.00, 'https://source.unsplash.com/featured/?espresso', TRUE),
        ('Американо', 'Американо з насиченим смаком.', 75.00, 'https://source.unsplash.com/featured/?americano,coffee', TRUE),
        ('Капучино', 'Капучино з молочною пінкою.', 95.00, 'https://source.unsplash.com/featured/?cappuccino', TRUE),
        ('Лате', 'Лате з м''яким смаком молока.', 105.00, 'https://source.unsplash.com/featured/?latte', TRUE),
        ('Матча-лате', 'Матча-лате з молоком.', 125.00, 'https://source.unsplash.com/featured/?matcha,latte', TRUE),
        ('Чай чорний', 'Чорний чай.', 75.00, 'https://source.unsplash.com/featured/?black,tea', TRUE),
        ('Чай зелений', 'Зелений чай.', 75.00, 'https://source.unsplash.com/featured/?green,tea', TRUE),
        ('Лимонад домашній', 'Лимонад з цитрусів та м''яти.', 105.00, 'https://source.unsplash.com/featured/?lemonade', TRUE),
        ('Апельсиновий фреш', 'Свіжовичавлений апельсиновий сік.', 125.00, 'https://source.unsplash.com/featured/?orange,juice', TRUE),
        ('Яблучний фреш', 'Свіжовичавлений яблучний сік.', 125.00, 'https://source.unsplash.com/featured/?apple,juice', TRUE),
        ('Морс ягідний', 'Ягідний морс.', 95.00, 'https://source.unsplash.com/featured/?berry,drink', TRUE),
        ('Вода мінеральна газована', 'Газована мінеральна вода.', 65.00, 'https://source.unsplash.com/featured/?sparkling,water', TRUE),
        ('Вода мінеральна негазована', 'Негазована мінеральна вода.', 65.00, 'https://source.unsplash.com/featured/?mineral,water', TRUE),
        ('Какао', 'Какао з молоком.', 95.00, 'https://source.unsplash.com/featured/?cocoa', TRUE),

        -- Вечірні спеціалітети (10) (частина також у Напоях / Основних)
        ('Мохіто', 'Класичний коктейль з м''ятою та лаймом.', 215.00, 'https://source.unsplash.com/featured/?mojito', TRUE),
        ('Маргарита', 'Текіла, лайм та тріпл-сек.', 235.00, 'https://source.unsplash.com/featured/?margarita,cocktail', TRUE),
        ('Апероль Шприц', 'Легкий аперитив з просекко.', 235.00, 'https://source.unsplash.com/featured/?aperol,spritz', TRUE),
        ('Негроні', 'Джин, кампарі та вермут.', 255.00, 'https://source.unsplash.com/featured/?negroni', TRUE),
        ('Олд Фешн', 'Бурбон, біттер та апельсин.', 265.00, 'https://source.unsplash.com/featured/?old,fashioned,cocktail', TRUE),
        ('Пиво крафтове', 'Крафтове світле/IPA (330 мл).', 135.00, 'https://source.unsplash.com/featured/?craft,beer', TRUE),
        ('Вино червоне келих', 'Сухе червоне вино (150 мл).', 165.00, 'https://source.unsplash.com/featured/?red,wine,glass', TRUE),
        ('Вино біле келих', 'Сухе біле вино (150 мл).', 165.00, 'https://source.unsplash.com/featured/?white,wine,glass', TRUE),
        ('Стейк Ті-Бон', 'Преміальний стейк ті-бон з розмарином.', 595.00, 'https://source.unsplash.com/featured/?t-bone,steak', TRUE),
        ('Устриці (6 шт.)', 'Устриці з лимоном та соусом.', 645.00, 'https://source.unsplash.com/featured/?oysters', TRUE),

        -- Дитяче меню (12)
        ('Курячі нагетси', 'Нагетси з курки з кетчупом.', 165.00, 'https://source.unsplash.com/featured/?chicken,nuggets', TRUE),
        ('Картопля фрі', 'Хрустка картопля фрі.', 105.00, 'https://source.unsplash.com/featured/?french,fries', TRUE),
        ('Міні-бургер', 'Міні-бургер з яловичиною та сиром.', 175.00, 'https://source.unsplash.com/featured/?mini,burger', TRUE),
        ('Паста з сиром', 'Паста з вершковим сирним соусом.', 155.00, 'https://source.unsplash.com/featured/?mac,and,cheese', TRUE),
        ('Курячі тефтелі з пюре', 'Тефтелі з курки з картопляним пюре.', 185.00, 'https://source.unsplash.com/featured/?meatballs,mash', TRUE),
        ('Суп-пюре гарбузовий', 'Ніжний гарбузовий крем-суп.', 145.00, 'https://source.unsplash.com/featured/?pumpkin,soup', TRUE),
        ('Піца Маргарита (міні)', 'Міні-піца з моцарелою та томатним соусом.', 185.00, 'https://source.unsplash.com/featured/?margherita,pizza', TRUE),
        ('Піца Пепероні (міні)', 'Міні-піца з пепероні та сиром.', 195.00, 'https://source.unsplash.com/featured/?pepperoni,pizza', TRUE),
        ('Пюре картопляне', 'Ніжне картопляне пюре.', 85.00, 'https://source.unsplash.com/featured/?mashed,potatoes', TRUE),
        ('Овочеві палички з соусом', 'Морква та огірок зі сметанним соусом.', 95.00, 'https://source.unsplash.com/featured/?vegetable,sticks', TRUE),
        ('Млинці з бананом', 'Млинці з бананом та шоколадним соусом.', 155.00, 'https://source.unsplash.com/featured/?banana,crepes', TRUE),
        ('Морозиво дитяче', 'Ванільне морозиво з посипкою.', 95.00, 'https://source.unsplash.com/featured/?vanilla,ice,cream', TRUE)
)
INSERT INTO dish(name, description, price, image_url, is_available)
SELECT sd.name, sd.description, sd.price::numeric(19,2), sd.image_url, sd.is_available
FROM seed_dishes sd
WHERE NOT EXISTS (
    SELECT 1 FROM dish d WHERE d.name = sd.name
);

-- 3) Dish -> menu mappings
WITH seed_links(dish_name, menu_name) AS (
    VALUES
        -- Закуски
        ('Брускета з томатами та базиліком', 'Закуски'),
        ('Брускета з лососем та крем-сиром', 'Закуски'),
        ('Тартар з яловичини', 'Закуски'),
        ('Тартар з лосося', 'Закуски'),
        ('Креветки темпура', 'Закуски'),
        ('Курячі крильця BBQ', 'Закуски'),
        ('Сирна тарілка', 'Закуски'),
        ('М''ясна тарілка', 'Закуски'),
        ('Хумус з пітою', 'Закуски'),
        ('Паштет з курячої печінки', 'Закуски'),
        ('Оселедець з цибулею та картоплею', 'Закуски'),
        ('Сало з часником та гірчицею', 'Закуски'),
        ('Вінегрет', 'Закуски'),
        ('Салат Грецький', 'Закуски'),
        ('Салат Цезар з куркою', 'Закуски'),
        ('Салат Цезар з креветками', 'Закуски'),
        ('Салат Капрезе', 'Закуски'),
        ('Олів''є з куркою', 'Закуски'),
        ('Форшмак', 'Закуски'),
        ('Мариновані оливки та маслини', 'Закуски'),

        -- Сніданки
        ('Сирники зі сметаною', 'Сніданки'),
        ('Вівсянка з ягодами та медом', 'Сніданки'),
        ('Гранола з йогуртом', 'Сніданки'),
        ('Яйця Бенедикт', 'Сніданки'),
        ('Омлет з сиром та зеленню', 'Сніданки'),
        ('Скрембл з лососем', 'Сніданки'),
        ('Шакшука', 'Сніданки'),
        ('Тост з авокадо', 'Сніданки'),
        ('Млинці з сиром', 'Сніданки'),
        ('Млинці з лососем', 'Сніданки'),
        ('Каша гречана з грибами', 'Сніданки'),
        ('Сендвіч з індичкою', 'Сніданки'),
        ('Круасан з мигдалем', 'Сніданки'),
        ('Круасан з шинкою та сиром', 'Сніданки'),
        ('Французькі тости', 'Сніданки'),
        ('Йогурт з фруктами', 'Сніданки'),

        -- Основні страви
        ('Борщ український', 'Основні страви'),
        ('Солянка м''ясна', 'Основні страви'),
        ('Курячий бульйон з локшиною', 'Основні страви'),
        ('Грибний крем-суп', 'Основні страви'),
        ('Юшка з риби', 'Основні страви'),
        ('Вареники з картоплею', 'Основні страви'),
        ('Вареники з вишнею', 'Основні страви'),
        ('Деруни зі сметаною', 'Основні страви'),
        ('Котлета по-київськи', 'Основні страви'),
        ('Голубці', 'Основні страви'),
        ('Плов з куркою', 'Основні страви'),
        ('Паста Карбонара', 'Основні страви'),
        ('Паста Болоньєзе', 'Основні страви'),
        ('Паста Альфредо з куркою', 'Основні страви'),
        ('Різото з грибами', 'Основні страви'),
        ('Різото з морепродуктами', 'Основні страви'),
        ('Лазанья болоньєзе', 'Основні страви'),
        ('Стейк Рібай', 'Основні страви'),
        ('Стейк Нью-Йорк', 'Основні страви'),
        ('Свинячі реберця BBQ', 'Основні страви'),
        ('Курка теріякі', 'Основні страви'),
        ('Куряче філе гриль', 'Основні страви'),
        ('Лосось гриль', 'Основні страви'),
        ('Філе тріски з пюре', 'Основні страви'),
        ('Мідії у вершковому соусі', 'Основні страви'),
        ('Бургер з яловичиною', 'Основні страви'),
        ('Курячий бургер', 'Основні страви'),
        ('Фіш-енд-чіпс', 'Основні страви'),
        ('Шніцель по-віденськи', 'Основні страви'),
        ('Бефстроганов', 'Основні страви'),
        ('Пельмені домашні', 'Основні страви'),
        ('Овочеве рагу', 'Основні страви'),
        ('Стейк з цвітної капусти', 'Основні страви'),
        ('Гречка з тушкованою яловичиною', 'Основні страви'),

        -- Десерти
        ('Київський торт', 'Десерти'),
        ('Медовик', 'Десерти'),
        ('Наполеон', 'Десерти'),
        ('Сирник львівський', 'Десерти'),
        ('Штрудель яблучний', 'Десерти'),
        ('Тірамісу', 'Десерти'),
        ('Панна котта', 'Десерти'),
        ('Чізкейк Нью-Йорк', 'Десерти'),
        ('Брауні з морозивом', 'Десерти'),
        ('Шоколадний фондан', 'Десерти'),
        ('Морозиво асорті', 'Десерти'),
        ('Профітролі', 'Десерти'),
        ('Макарони', 'Десерти'),
        ('Чізкейк з чорницею', 'Десерти'),
        ('Пиріг з вишнею', 'Десерти'),
        ('Крем-брюле', 'Десерти'),

        -- Напої
        ('Еспресо', 'Напої'),
        ('Американо', 'Напої'),
        ('Капучино', 'Напої'),
        ('Лате', 'Напої'),
        ('Матча-лате', 'Напої'),
        ('Чай чорний', 'Напої'),
        ('Чай зелений', 'Напої'),
        ('Лимонад домашній', 'Напої'),
        ('Апельсиновий фреш', 'Напої'),
        ('Яблучний фреш', 'Напої'),
        ('Морс ягідний', 'Напої'),
        ('Вода мінеральна газована', 'Напої'),
        ('Вода мінеральна негазована', 'Напої'),
        ('Какао', 'Напої'),

        -- Вечірні спеціалітети (+ частина також Напої/Основні)
        ('Мохіто', 'Вечірні спеціалітети'),
        ('Маргарита', 'Вечірні спеціалітети'),
        ('Апероль Шприц', 'Вечірні спеціалітети'),
        ('Негроні', 'Вечірні спеціалітети'),
        ('Олд Фешн', 'Вечірні спеціалітети'),
        ('Пиво крафтове', 'Вечірні спеціалітети'),
        ('Вино червоне келих', 'Вечірні спеціалітети'),
        ('Вино біле келих', 'Вечірні спеціалітети'),
        ('Стейк Ті-Бон', 'Вечірні спеціалітети'),
        ('Устриці (6 шт.)', 'Вечірні спеціалітети'),
        ('Мохіто', 'Напої'),
        ('Маргарита', 'Напої'),
        ('Апероль Шприц', 'Напої'),
        ('Негроні', 'Напої'),
        ('Олд Фешн', 'Напої'),
        ('Пиво крафтове', 'Напої'),
        ('Вино червоне келих', 'Напої'),
        ('Вино біле келих', 'Напої'),
        ('Стейк Ті-Бон', 'Основні страви'),
        ('Устриці (6 шт.)', 'Закуски'),

        -- Перетини сніданків з напоями
        ('Еспресо', 'Сніданки'),
        ('Американо', 'Сніданки'),
        ('Капучино', 'Сніданки'),
        ('Лате', 'Сніданки'),
        ('Чай чорний', 'Сніданки'),
        ('Чай зелений', 'Сніданки'),
        ('Апельсиновий фреш', 'Сніданки'),
        ('Яблучний фреш', 'Сніданки'),
        ('Какао', 'Сніданки'),

        -- Дитяче меню
        ('Курячі нагетси', 'Дитяче меню'),
        ('Картопля фрі', 'Дитяче меню'),
        ('Міні-бургер', 'Дитяче меню'),
        ('Паста з сиром', 'Дитяче меню'),
        ('Курячі тефтелі з пюре', 'Дитяче меню'),
        ('Суп-пюре гарбузовий', 'Дитяче меню'),
        ('Піца Маргарита (міні)', 'Дитяче меню'),
        ('Піца Пепероні (міні)', 'Дитяче меню'),
        ('Пюре картопляне', 'Дитяче меню'),
        ('Овочеві палички з соусом', 'Дитяче меню'),
        ('Млинці з бананом', 'Дитяче меню'),
        ('Морозиво дитяче', 'Дитяче меню'),
        ('Картопля фрі', 'Закуски'),
        ('Курячі нагетси', 'Закуски')
)
INSERT INTO dish_menus(dish_id, menu_id)
SELECT d.id, m.id
FROM seed_links sl
JOIN dish d ON d.name = sl.dish_name
JOIN menu m ON m.name = sl.menu_name
WHERE NOT EXISTS (
    SELECT 1
    FROM dish_menus dm
    WHERE dm.dish_id = d.id AND dm.menu_id = m.id
);

-- 4) Dish tags (3–6 per dish, safe on re-run)
WITH seed_tags(dish_name, tag) AS (
    VALUES
        -- Закуски
        ('Брускета з томатами та базиліком', 'appetizer'),
        ('Брускета з томатами та базиліком', 'european'),
        ('Брускета з томатами та базиліком', 'vegetarian'),
        ('Брускета з томатами та базиліком', 'bread'),
        ('Брускета з лососем та крем-сиром', 'appetizer'),
        ('Брускета з лососем та крем-сиром', 'seafood'),
        ('Брускета з лососем та крем-сиром', 'european'),
        ('Тартар з яловичини', 'appetizer'),
        ('Тартар з яловичини', 'beef'),
        ('Тартар з яловичини', 'european'),
        ('Тартар з лосося', 'appetizer'),
        ('Тартар з лосося', 'seafood'),
        ('Тартар з лосося', 'fresh'),
        ('Креветки темпура', 'appetizer'),
        ('Креветки темпура', 'seafood'),
        ('Креветки темпура', 'fried'),
        ('Курячі крильця BBQ', 'appetizer'),
        ('Курячі крильця BBQ', 'chicken'),
        ('Курячі крильця BBQ', 'bbq'),
        ('Сирна тарілка', 'appetizer'),
        ('Сирна тарілка', 'cheese'),
        ('Сирна тарілка', 'share'),
        ('М''ясна тарілка', 'appetizer'),
        ('М''ясна тарілка', 'meat'),
        ('М''ясна тарілка', 'share'),
        ('Хумус з пітою', 'appetizer'),
        ('Хумус з пітою', 'vegan'),
        ('Хумус з пітою', 'healthy'),
        ('Паштет з курячої печінки', 'appetizer'),
        ('Паштет з курячої печінки', 'ukrainian'),
        ('Паштет з курячої печінки', 'liver'),
        ('Оселедець з цибулею та картоплею', 'ukrainian'),
        ('Оселедець з цибулею та картоплею', 'fish'),
        ('Оселедець з цибулею та картоплею', 'appetizer'),
        ('Сало з часником та гірчицею', 'ukrainian'),
        ('Сало з часником та гірчицею', 'pork'),
        ('Сало з часником та гірчицею', 'appetizer'),
        ('Вінегрет', 'ukrainian'),
        ('Вінегрет', 'salad'),
        ('Вінегрет', 'vegetarian'),
        ('Салат Грецький', 'salad'),
        ('Салат Грецький', 'european'),
        ('Салат Грецький', 'vegetarian'),
        ('Салат Цезар з куркою', 'salad'),
        ('Салат Цезар з куркою', 'chicken'),
        ('Салат Цезар з куркою', 'european'),
        ('Салат Цезар з креветками', 'salad'),
        ('Салат Цезар з креветками', 'seafood'),
        ('Салат Цезар з креветками', 'european'),
        ('Салат Капрезе', 'salad'),
        ('Салат Капрезе', 'vegetarian'),
        ('Салат Капрезе', 'italian'),
        ('Олів''є з куркою', 'ukrainian'),
        ('Олів''є з куркою', 'salad'),
        ('Олів''є з куркою', 'chicken'),
        ('Форшмак', 'ukrainian'),
        ('Форшмак', 'fish'),
        ('Форшмак', 'appetizer'),
        ('Мариновані оливки та маслини', 'appetizer'),
        ('Мариновані оливки та маслини', 'vegetarian'),
        ('Мариновані оливки та маслини', 'snack'),

        -- Сніданки
        ('Сирники зі сметаною', 'breakfast'),
        ('Сирники зі сметаною', 'ukrainian'),
        ('Сирники зі сметаною', 'dessert'),
        ('Вівсянка з ягодами та медом', 'breakfast'),
        ('Вівсянка з ягодами та медом', 'healthy'),
        ('Вівсянка з ягодами та медом', 'vegetarian'),
        ('Гранола з йогуртом', 'breakfast'),
        ('Гранола з йогуртом', 'healthy'),
        ('Гранола з йогуртом', 'vegetarian'),
        ('Яйця Бенедикт', 'breakfast'),
        ('Яйця Бенедикт', 'eggs'),
        ('Яйця Бенедикт', 'european'),
        ('Омлет з сиром та зеленню', 'breakfast'),
        ('Омлет з сиром та зеленню', 'eggs'),
        ('Омлет з сиром та зеленню', 'vegetarian'),
        ('Скрембл з лососем', 'breakfast'),
        ('Скрембл з лососем', 'seafood'),
        ('Скрембл з лососем', 'eggs'),
        ('Шакшука', 'breakfast'),
        ('Шакшука', 'eggs'),
        ('Шакшука', 'spicy'),
        ('Тост з авокадо', 'breakfast'),
        ('Тост з авокадо', 'healthy'),
        ('Тост з авокадо', 'vegetarian'),
        ('Млинці з сиром', 'breakfast'),
        ('Млинці з сиром', 'ukrainian'),
        ('Млинці з сиром', 'sweet'),
        ('Млинці з лососем', 'breakfast'),
        ('Млинці з лососем', 'seafood'),
        ('Млинці з лососем', 'ukrainian'),
        ('Каша гречана з грибами', 'breakfast'),
        ('Каша гречана з грибами', 'ukrainian'),
        ('Каша гречана з грибами', 'vegetarian'),
        ('Сендвіч з індичкою', 'breakfast'),
        ('Сендвіч з індичкою', 'sandwich'),
        ('Сендвіч з індичкою', 'turkey'),
        ('Круасан з мигдалем', 'breakfast'),
        ('Круасан з мигдалем', 'pastry'),
        ('Круасан з мигдалем', 'sweet'),
        ('Круасан з шинкою та сиром', 'breakfast'),
        ('Круасан з шинкою та сиром', 'pastry'),
        ('Круасан з шинкою та сиром', 'meat'),
        ('Французькі тости', 'breakfast'),
        ('Французькі тости', 'sweet'),
        ('Французькі тости', 'european'),
        ('Йогурт з фруктами', 'breakfast'),
        ('Йогурт з фруктами', 'healthy'),
        ('Йогурт з фруктами', 'vegetarian'),

        -- Основні страви (вибірково, але достатньо для рекомендацій/тегів)
        ('Борщ український', 'ukrainian'),
        ('Борщ український', 'soup'),
        ('Борщ український', 'beet'),
        ('Солянка м''ясна', 'soup'),
        ('Солянка м''ясна', 'meat'),
        ('Солянка м''ясна', 'ukrainian'),
        ('Курячий бульйон з локшиною', 'soup'),
        ('Курячий бульйон з локшиною', 'chicken'),
        ('Курячий бульйон з локшиною', 'comfort'),
        ('Грибний крем-суп', 'soup'),
        ('Грибний крем-суп', 'mushroom'),
        ('Грибний крем-суп', 'vegetarian'),
        ('Вареники з картоплею', 'ukrainian'),
        ('Вареники з картоплею', 'dumplings'),
        ('Вареники з картоплею', 'vegetarian'),
        ('Котлета по-київськи', 'ukrainian'),
        ('Котлета по-київськи', 'chicken'),
        ('Котлета по-київськи', 'classic'),
        ('Паста Карбонара', 'italian'),
        ('Паста Карбонара', 'pasta'),
        ('Паста Карбонара', 'european'),
        ('Різото з грибами', 'italian'),
        ('Різото з грибами', 'risotto'),
        ('Різото з грибами', 'vegetarian'),
        ('Стейк Рібай', 'beef'),
        ('Стейк Рібай', 'grill'),
        ('Стейк Рібай', 'premium'),
        ('Лосось гриль', 'seafood'),
        ('Лосось гриль', 'grill'),
        ('Лосось гриль', 'healthy'),
        ('Бургер з яловичиною', 'burger'),
        ('Бургер з яловичиною', 'beef'),
        ('Бургер з яловичиною', 'streetfood'),
        ('Шніцель по-віденськи', 'european'),
        ('Шніцель по-віденськи', 'meat'),
        ('Шніцель по-віденськи', 'fried'),
        ('Овочеве рагу', 'vegetarian'),
        ('Овочеве рагу', 'healthy'),
        ('Овочеве рагу', 'stew'),

        -- Десерти
        ('Київський торт', 'dessert'),
        ('Київський торт', 'ukrainian'),
        ('Київський торт', 'cake'),
        ('Медовик', 'dessert'),
        ('Медовик', 'cake'),
        ('Медовик', 'classic'),
        ('Тірамісу', 'dessert'),
        ('Тірамісу', 'italian'),
        ('Тірамісу', 'coffee'),
        ('Крем-брюле', 'dessert'),
        ('Крем-брюле', 'european'),
        ('Крем-брюле', 'classic'),

        -- Напої
        ('Еспресо', 'drink'),
        ('Еспресо', 'coffee'),
        ('Еспресо', 'hot'),
        ('Капучино', 'drink'),
        ('Капучино', 'coffee'),
        ('Капучино', 'hot'),
        ('Чай зелений', 'drink'),
        ('Чай зелений', 'tea'),
        ('Чай зелений', 'hot'),
        ('Лимонад домашній', 'drink'),
        ('Лимонад домашній', 'cold'),
        ('Лимонад домашній', 'citrus'),
        ('Апельсиновий фреш', 'drink'),
        ('Апельсиновий фреш', 'juice'),
        ('Апельсиновий фреш', 'healthy'),

        -- Вечірні
        ('Мохіто', 'drink'),
        ('Мохіто', 'cocktail'),
        ('Мохіто', 'alcohol'),
        ('Негроні', 'drink'),
        ('Негроні', 'cocktail'),
        ('Негроні', 'alcohol'),
        ('Пиво крафтове', 'drink'),
        ('Пиво крафтове', 'beer'),
        ('Пиво крафтове', 'alcohol'),
        ('Стейк Ті-Бон', 'beef'),
        ('Стейк Ті-Бон', 'grill'),
        ('Стейк Ті-Бон', 'premium'),
        ('Устриці (6 шт.)', 'seafood'),
        ('Устриці (6 шт.)', 'appetizer'),
        ('Устриці (6 шт.)', 'premium'),

        -- Дитяче
        ('Курячі нагетси', 'kids'),
        ('Курячі нагетси', 'chicken'),
        ('Курячі нагетси', 'fried'),
        ('Паста з сиром', 'kids'),
        ('Паста з сиром', 'pasta'),
        ('Паста з сиром', 'cheese'),
        ('Морозиво дитяче', 'kids'),
        ('Морозиво дитяче', 'dessert'),
        ('Морозиво дитяче', 'cold')
)
INSERT INTO dish_tags(dish_id, tag)
SELECT d.id, st.tag
FROM seed_tags st
JOIN dish d ON d.name = st.dish_name
WHERE NOT EXISTS (
    SELECT 1
    FROM dish_tags dt
    WHERE dt.dish_id = d.id AND dt.tag = st.tag
);

